# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-09-07 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passwd',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='u_name',
            new_name='password',
        ),
        migrations.AlterField(
            model_name='emp',
            name='name',
            field=models.CharField(default='qwe', max_length=30),
        ),
    ]
