# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-09-07 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0002_auto_20200907_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='u_name',
            field=models.CharField(default='zs', max_length=32),
        ),
        migrations.AlterField(
            model_name='emp',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
