# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-09-07 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0003_auto_20200907_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='aa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
    ]
