# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-09-07 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0004_aa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='aa',
        ),
        migrations.RemoveField(
            model_name='emp',
            name='u_name',
        ),
        migrations.AlterField(
            model_name='emp',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='emp',
            table='staff',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
