# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-09-07 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0005_auto_20200907_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(),
        ),
    ]
