# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-09-07 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0006_auto_20200907_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tickek',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
